### ISSUE TITLE
visualization : module can't be loaded

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#102]
Hi Nicolas, 
Using the latest nightly (gd5a0dca) on Windows 10, I can't load any extra visualization module.
![Capture](https://user-images.githubusercontent.com/41745996/160440995-366515df-4507-403f-bf21-dd715f56db2a.PNG)

Thanks for your help
Simon

**Comment by n-elie** [comment]
Hi Simon,
This is fixed by 10ffc1d
Nicolas
