### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by i-guigon** [metgem/metgem#104]
Hi there

Thank you again for the tool and for your help!

When I import a list of spectra, when I try to click in the "nodes" table on any line the software closes and the terminal indicates "segmentation fault". Then when I reopen the software and do exactly the same things again, no crash.

I've experimented this each time I import a list of spectra.
I had this issue with release 1.3.6 and again with the version of code I've downloaded today (31/03/2022).

Thanks for your help.

**Comment by n-elie** [comment]
Is it fixed by [e3cb682](https://github.com/metgem/metgem/commit/e3cb682710ad31827ae95b7c29872cca528840f2) ?
