### ISSUE TITLE
Update ISDB sources

### ISSUE THREAD

**Issue by oolonek** [metgem/metgem#108]
The ISDB sources fetched her https://github.com/metgem/metgem/blob/master/metgem_app/plugins/isdb.py are not up to date.
Latest ISDB version (wider coverage and merged energy levels) can be fetched at [10.5281/zenodo.5607185](https://doi.org/10.5281/zenodo.5607185)

Would be nice to have the source (Zenodo doi for ex.) and version number also in the app : 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/2760049/174425080-2a46b817-72ac-4a3b-87e1-0605db389a8c.png">

**Comment by n-elie** [comment]
Thanks for your message. The plugin has been updated
![image](https://user-images.githubusercontent.com/40382614/174556003-0ee6b045-e88d-4c3c-9641-175d3bdfcb4a.png)
