### ISSUE TITLE
Problem to import Metadata

### ISSUE THREAD

**Issue by hfchang12** [metgem/metgem#117]
Hello,

I would like to import Metadata from a CSV file but it doesn't work (see capture attached).
Could you help me with this issue?

Thank you in advance,
Cordially,
Hsinfang

<img width="524" alt="Screenshot 2023-11-10 at 3 56 26 PM" src="https://github.com/metgem/metgem/assets/97486069/3f6fdc9e-0cf2-49e8-a00a-9e0b451ebf44">

**Comment by n-elie** [comment]
Hello, this has been fixed in 43d8599 a few days ago. I plan to release a corrective version today or tomorrow

**Comment by hfchang12** [comment]
Thank you!

**Comment by n-elie** [comment]
@hfchang12 It took a bit more time, but [version 1.4.3](/metgem/metgem/releases/v1.4.3) that includes a fix for this was released today.
