### ISSUE TITLE
Issue after installation

### ISSUE THREAD

**Issue by Shrvvmz** [metgem/metgem#118]
Hi!
Unfortunately, I am not able to open MetGem after installing the latest version. It stops at 30% giving an error message (see image attached)

![IssueMetGem](https://github.com/metgem/metgem/assets/117981247/88c89a63-3baf-4146-8834-acdbb4c953be)

I hope you can help me with this.

Best regards,
Fabian

**Comment by n-elie** [comment]
Hello,

Please uninstall MetGem and make sure that the software directory is empty after uninstallation (C:\Program Files\MetGem).
Then reinstall again.
This should work after that

Regards,
Nicolas

**Comment by Shrvvmz** [comment]
Dear Nicolas,
thank you very much for your response! Now it is working perfectly fine.
Best regards,
Fabian

Von: Nicolas Elie ***@***.***>
Gesendet: Dienstag, 20. Februar 2024 17:08
An: metgem/metgem ***@***.***>
Cc: Hammerle, Fabian Jürgen ***@***.***>; Author ***@***.***>
Betreff: Re: [metgem/metgem] Issue after installation (Issue #118)


Hello,

Please uninstall MetGem and make sure that the software directory is empty after uninstallation (C:\Program Files\MetGem).
Then reinstall again.
This should work after that

Regards,
Nicolas
