### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by OrianneBrel** [metgem/metgem#80]
Idées d'options à rajouter : 
- [x] possibilité de choisir les couleurs pour les colonnes/pie-charts et pas seulement un nuancier pré-établi
- [x] pouvoir sauvegarder les changements effectués sur la visualisation (couleur des colonnes pour les pie-charts, label des noeuds ...)
- [x] pouvoir déplacer les colonnes
- [x] avoir les mêmes couleurs sur les en-têtes de colonnes et sur les pie-charts
- [x] comparaison des spectres du réseau et du match dans les bdd, comme ce qui existe actuellement pour comparer deux spectres du réseau.

**Comment by n-elie** [comment]
Hability to move columns in nodes and edges tables has been added in 8d2c156. Will be in v1.1

**Comment by n-elie** [comment]
- A new dialog has been added in ae3cf54 to fine tune the selection of colors used for pie charts:
![image](https://user-images.githubusercontent.com/40382614/53251213-710deb80-36bc-11e9-81bd-c3968af29361.png)
- Visualisation of colors in table headers has been improved:
![image](https://user-images.githubusercontent.com/40382614/53251268-8f73e700-36bc-11e9-9599-ceee23603c08.png)
This will be in 1.2

**Comment by n-elie** [comment]
- In the database dialog, the node spectrum is now visible as a reference in the spectrum view.
- Columns mappings mappings can now be saved and reloaded
