### ISSUE TITLE
Impossible to mount .dmg

### ISSUE THREAD

**Issue by Adafede** [metgem/metgem#81]
Hi,

Could you upload a .dmg version? It is days I'm trying to mount it but it seems that due to igraph versions and so on it is now broken. (failures opening the obtained .dmg)

Thanks a lot in advance

**Comment by n-elie** [comment]
Hello,

Thank you for your interest.
A Mac OS release was uploaded for the very first version of MetGem but this is now obsolete.

I don't have any Mac so it's difficult to support.
All C/C++ parts compile successfully in Mac OS. It's just a matter of packaging everything.
Any help would be appreciated.

**Comment by Adafede** [comment]
Hello,

Quick update: 
After some searches (and sweat), two things were missing:

1) Manual install of igraph (https://pypi.org/project/python-igraph/#files))
2) The "convert" command for the icon isn't common on Mac so had to install it (therefore: Xcode, Macports are needed + imagemagick (brew install imagemagick)

The whole thing then mounts without any error...buuuuuut...when opening the program, crashes at 15% loading (don't know if it helps). 

It's getting better!

**Comment by n-elie** [comment]
Hello,

I'm so glad to read that!

I think it would be easier to just provide icon for mac in icns format than require imagemagick to convert them. I will change this soon.

Crash at 15% loading could mean you're missing pyarrow library. Do you have any output if you launch the gui script from a terminal? There is a list of required dependencies in requirements.txt or environment.yml if you are using conda.

**Comment by Adafede** [comment]
Actually all needed libraries are loaded according to the requiremements.txt...so don't know ;(

But going through the whole process again, I noticed some errors on the last step:

(packaging) Adriano:packaging rutza$ invoke build
38 INFO: PyInstaller: 3.4
38 INFO: Python: 3.7.1
47 INFO: Platform: Darwin-18.2.0-x86_64-i386-64bit
53 INFO: UPX is not available.
127 INFO: Extending PYTHONPATH with paths
['/Users/rutza/Downloads/metgem-1.1']
127 INFO: checking Analysis
127 INFO: Building Analysis because Analysis-00.toc is non existent
127 INFO: Initializing module dependency graph...
129 INFO: Initializing module graph hooks...
130 INFO: Analyzing base_library.zip ...
2500 INFO: Analyzing hidden import 'PyQt5.QtOpenGL'
2511 INFO: running Analysis Analysis-00.toc
2516 INFO: Caching module hooks...
2519 INFO: Analyzing ../gui.py
2896 INFO: Processing pre-find module path hook   distutils
3588 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
3898 INFO: Processing pre-find module path hook   site
3898 INFO: site: retargeting to fake-dir '/Users/rutza/Downloads/metgem-1.1/packaging/lib/python3.7/site-packages/PyInstaller/fake-modules'
5826 INFO: Processing pre-safe import module hook   six.moves
21898 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
22474 INFO: Processing pre-find module path hook   PyQt5.uic.port_v3
22486 INFO: Processing pre-find module path hook   PyQt5.uic.port_v2
24439 INFO: Loading module hooks...
24439 INFO: Loading module hook "hook-scipy.linalg.py"...
24440 INFO: Loading module hook "hook-zmq.py"...
24599 INFO: Loading module hook "hook-sqlite3.py"...
24645 INFO: Loading module hook "hook-pkg_resources.py"...
24873 INFO: Processing pre-safe import module hook   win32com
25027 INFO: Loading module hook "hook-pandas.py"...
26008 INFO: Loading module hook "hook-pandas.py"...
26011 INFO: Loading module hook "hook-PyQt5.py"...
26040 INFO: Loading module hook "hook-PyQt5.py"...
26041 INFO: Loading module hook "hook-scipy.py"...
26042 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
26042 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
26043 INFO: Loading module hook "hook-pytz.py"...
26062 INFO: Loading module hook "hook-encodings.py"...
26114 INFO: Loading module hook "hook-IPython.py"...
26126 INFO: Excluding import 'PyQt4'
26131 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
26132 INFO: Excluding import 'matplotlib'
26136 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
26136 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
26136 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
26136 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
26137 INFO:   Removing import of matplotlib from module IPython.lib.latextools
26137 INFO:   Removing import of matplotlib.mathtext from module IPython.lib.latextools
26137 INFO: Excluding import 'PyQt5'
26142 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
26142 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
26142 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
26142 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
26142 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
26142 INFO: Excluding import 'PySide'
26147 INFO:   Removing import of PySide from module IPython.external.qt_loaders
26148 INFO: Excluding import 'tkinter'
26153 INFO:   Removing import of tkinter from module IPython.lib.clipboard
26155 INFO: Excluding import 'gtk'
26160 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
26163 INFO: Loading module hook "hook-setuptools.py"...
26527 INFO: Loading module hook "hook-matplotlib.py"...
26705 INFO: Loading module hook "hook-PyQt5.QtOpenGL.py"...
26813 INFO: Loading module hook "hook-xml.dom.domreg.py"...
26813 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
26839 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
26883 INFO: Loading module hook "hook-jedi.py"...
26887 INFO: Loading module hook "hook-jedi.py"...
26890 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
26890 INFO: Loading module hook "hook-scipy.io.matlab.py"...
26890 INFO: Loading module hook "hook-certifi.py"...
26891 INFO: Loading module hook "hook-matplotlib.backends.py"...
27287 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that cairocffi or pycairo is installed
27505 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
27833 INFO:   Matplotlib backend "MacOSX": ignored
    Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
28386 INFO:   Matplotlib backend "nbAgg": added
28765 INFO:   Matplotlib backend "Qt4Agg": added
28993 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
29391 INFO:   Matplotlib backend "Qt5Agg": added
29614 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
29941 INFO:   Matplotlib backend "TkAgg": added
30246 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
30527 INFO:   Matplotlib backend "WebAgg": added
30821 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
31041 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
31253 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
31471 INFO:   Matplotlib backend "agg": added
31688 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
31979 INFO:   Matplotlib backend "pdf": added
32274 INFO:   Matplotlib backend "pgf": added
32502 INFO:   Matplotlib backend "ps": added
32719 INFO:   Matplotlib backend "svg": added
33005 INFO:   Matplotlib backend "template": added
33186 INFO: Loading module hook "hook-sklearn.metrics.cluster.py"...
33196 WARNING: Hidden import "sklearn.utils.sparsetools._graph_validation" not found!
33196 WARNING: Hidden import "sklearn.utils.sparsetools._graph_tools" not found!
33197 INFO: Loading module hook "hook-sqlalchemy.py"...
33321 INFO:   Found 4 sqlalchemy hidden imports
33322 WARNING: Hidden import "MySQLdb" not found!
33323 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
33393 INFO: Excluding import 'sqlalchemy.testing'
33398 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
33399 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing
33399 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
33399 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
33399 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
33399 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
33399 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
33399 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
33399 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
33399 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
33400 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
33400 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
33400 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
33400 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
33400 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
33400 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
33400 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
33400 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
33401 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
33401 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
33402 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
33402 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
33402 INFO: Loading module hook "hook-sqlalchemy.py"...
33414 INFO:   Found 2 sqlalchemy hidden imports
33426 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
33429 INFO: Excluding import 'sqlalchemy.testing'
33437 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
33460 INFO: Loading module hook "hook-lxml.etree.py"...
33460 INFO: Loading module hook "hook-sysconfig.py"...
33467 INFO: Loading module hook "hook-PyQt5.uic.py"...
33468 INFO: Loading module hook "hook-numpy.core.py"...
33471 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
33475 INFO: Loading module hook "hook-xml.py"...
33475 INFO: Loading module hook "hook-pydoc.py"...
33476 INFO: Loading module hook "hook-numpy.py"...
33477 INFO: Loading module hook "hook-PyQt5.QtTest.py"...
33504 INFO: Loading module hook "hook-distutils.py"...
33504 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
33514 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
33549 INFO: Loading module hook "hook-pygments.py"...
34624 INFO: Loading module hook "hook-parso.py"...
34627 INFO: Loading module hook "hook-qtconsole.py"...
34629 INFO: Loading module hook "hook-igraph.py"...
34630 INFO: Loading module hook "hook-pyarrow.py"...
34646 WARNING: Hidden import "pyarrow.formatting" not found!
34646 WARNING: Hidden import "pyarrow.compat.*" not found!
34646 INFO: Loading module hook "hook-sklearn.manifold.py"...
34680 WARNING: Hidden import "sklearn.tree._treesklearn.tree.tree" not found!
34767 INFO: Looking for ctypes DLLs
34786 WARNING: library user32 required via ctypes not found
34821 WARNING: library librt.so.1 required via ctypes not found
34827 INFO: Analyzing run-time hooks ...
34827 INFO: Including custom run-time hook 'rthooks/1_pyi_rth_multiprocessing.py'
34829 INFO: Including custom run-time hook 'rthooks/2_pyi_rth_qtconsole.py'
34847 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
34849 INFO: Including run-time hook 'pyi_rth_pkgres.py'
34850 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
34851 INFO: Including run-time hook 'pyi_rth_mpldata.py'
34852 INFO: Including run-time hook 'pyi_rth_traitlets.py'
34853 INFO: Including run-time hook 'pyi_rth_qt5.py'
34897 INFO: Looking for dynamic libraries
35029 ERROR: Can not find path ./libtbb.dylib (needed by /Users/rutza/anaconda3/lib/libmkl_tbb_thread.dylib)
35043 ERROR: Can not find path ./libarrow_boost_system.dylib (needed by /Users/rutza/Downloads/metgem-1.1/packaging/lib/python3.7/site-packages/pyarrow/libarrow_boost_filesystem.dylib)
35087 ERROR: Can not find path ./libarrow_boost_system.dylib (needed by /Users/rutza/Downloads/metgem-1.1/packaging/lib/python3.7/site-packages/pyarrow/libarrow_boost_filesystem.1.65.1.dylib)
36357 ERROR: Can not find path ./libarrow_boost_system.dylib (needed by /Users/rutza/Downloads/metgem-1.1/packaging/lib/python3.7/site-packages/pyarrow/libarrow_boost_filesystem.dylib)
36510 INFO: Looking for eggs
36510 INFO: Python library not in binary dependencies. Doing additional searching...
36513 INFO: Using Python library /Users/rutza/anaconda3/lib/libpython3.7m.dylib
36541 INFO: Warnings written to /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/warn-gui.txt
36741 INFO: Graph cross-reference written to /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/xref-gui.html
36833 INFO: Appending 'binaries' from .spec
36833 INFO: Appending 'datas' from .spec
36844 INFO: checking PYZ
36845 INFO: Building PYZ because PYZ-00.toc is non existent
36845 INFO: Building PYZ (ZlibArchive) /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/PYZ-00.pyz
38915 INFO: Building PYZ (ZlibArchive) /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/PYZ-00.pyz completed successfully.
38981 INFO: checking PKG
38981 INFO: Building PKG because PKG-00.toc is non existent
38982 INFO: Building PKG (CArchive) PKG-00.pkg
39020 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
39021 INFO: Bootloader /Users/rutza/Downloads/metgem-1.1/packaging/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
39021 INFO: checking EXE
39022 INFO: Building EXE because EXE-00.toc is non existent
39022 INFO: Building EXE from EXE-00.toc
39022 INFO: Appending archive to EXE /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/MetGem
39032 INFO: Fixing EXE for code signing /Users/rutza/Downloads/metgem-1.1/packaging/build/gui/MetGem
39035 INFO: Building EXE from EXE-00.toc completed successfully.
39037 INFO: checking COLLECT
39037 INFO: Building COLLECT because COLLECT-00.toc is non existent
39037 INFO: Building COLLECT COLLECT-00.toc
50698 INFO: Building COLLECT COLLECT-00.toc completed successfully.
50718 INFO: checking BUNDLE
50718 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
50718 INFO: Building BUNDLE BUNDLE-00.toc
60525 INFO: moving BUNDLE data files to Resource directory
/var/folders/9r/vd1zlj3j0nb8ksm1kb_9stjc0000gp/T/tmp7z1lk7bc ~/Downloads/metgem-1.1/packaging
~/Downloads/metgem-1.1/packaging
ditto: /Volumes/MetGem/MetGem/examples/Codiaeum.mgf: No space left on device
(packaging) Adriano:packaging rutza$ 


Maybe those lib are responsible of the problem...tried reinstalling some with conda but still does not work...

**Comment by Adafede** [comment]
Yes...not a solution sadly! Still crashes at 15%

**Comment by n-elie** [comment]
Hello,

I just saw your edit. So you are now missing the 'libmetgem' library which is used for cosine calculations. You will have to compile it by yourself. Source code can be found here : https://github.com/metgem/libmetgem
It depends only on numpy and cython. Compilation should be as easy as ```conda build --python=3.6``` (replace 3.6 by your python version). Then, to install it use ```conda install libmetgem --use-local```.

Next step will be to compile PyQtNetworkView which is the lib used for graph visualisation. You can found it here: https://github.com/metgem/PyQtNetworkView
Compilation could be done using ```conda build --python=3.6 -c conda-forge```. Then, to install: ```conda install pyqtnetworkview --use-local```.

**Comment by Adafede** [comment]
Hi,

Thank you very much for your reply. I did follow your suggestions and now I'm at 75%, not 70% anymore..sooon!

First error was giving me Fa2 missing, which I installed manually and went fine. 
Then, for PyQtNetworkView, I had first to install SipDisutils manually (https://stackoverflow.com/questions/51420803/modulenotfounderror-no-module-named-sipdistutils-while-install-python-poppler)  but probably wasn't the right solution since PyQtNetworkView does not install properly even after it. I'm so still stuck at 

(packaging) Adriano:packaging rutza$ python ../gui.py
Traceback (most recent call last):
  File "../gui.py", line 57, in <module>
    main()
  File "../gui.py", line 26, in main
    from splash import splash
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/splash.py", line 130, in <module>
    import lib.ui
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/lib/ui/__init__.py", line 1, in <module>
    from .main_window import MainWindow
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/lib/ui/main_window.py", line 29, in <module>
    from PyQtNetworkView import NetworkScene, style_from_css, style_to_cytoscape, disable_opengl
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/packaging/lib/python3.7/site-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
ModuleNotFoundError: No module named 'PyQtNetworkView'

or after manually dragging it,

(packaging) Adriano:packaging rutza$ python ../gui.py
Traceback (most recent call last):
  File "../gui.py", line 57, in <module>
    main()
  File "../gui.py", line 26, in main
    from splash import splash
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/splash.py", line 130, in <module>
    import lib.ui
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/lib/ui/__init__.py", line 1, in <module>
    from .main_window import MainWindow
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/lib/ui/main_window.py", line 29, in <module>
    from PyQtNetworkView import NetworkScene, style_from_css, style_to_cytoscape, disable_opengl
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/packaging/lib/python3.7/site-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/packaging/lib/python3.7/site-packages/PyQtNetworkView/__init__.py", line 8, in <module>
    from .NetworkView import (Node, Edge, RADIUS,
  File "/Users/rutza/Downloads/metgem-1.2RC3 3/packaging/lib/python3.7/site-packages/pluginbase.py", line 439, in plugin_import
    fromlist, level)
ModuleNotFoundError: No module named 'PyQtNetworkView.NetworkView'

I think it is related to something missing with the manual install but you surely know best, thank you very much for your help!

**Comment by n-elie** [comment]
PyQt should be installed using conda not by pip. Conda build is bundled with sipdistutils. It is usually a bad idea to mix pypi and conda packages.

Also, I see that you are using python 3.7. This is fine, the windows version is packaged with this version. But did you compiled PyQtNetworkView for 3.7? Command should be `conda build --python=3.7 -c conda-forge`.

Not sure this will help but this is the only ideas I have for now.

Again, thank you for your interest. You are almost done.

**Comment by Adafede** [comment]
I absolutely understand what you mean but I'm having unresolved issues with Anaconda with the previous steps (pyarrow, igraph...that's why I avoided it). I tried it again and yet stuck even sooner...I had some hopes while compiling missing modules as you said but still not getting to the point ;(

My apologies, it is a shame...

**Comment by Adafede** [comment]
Ok...still fighting with it...managed to almost get till the end! Libmetgem done but still having problems with PyQtNetworkView. First, when compiling it I have some headers issues (warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
      the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]) i tried to fix, but then when "hopefully" complied, the installation gives me

(base) Adriano:packaging rutza$ conda install pyqtnetworkview --use-local
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyqtnetworkview -> tinycss2

**Comment by n-elie** [comment]
Woah, good news !
This one should be easy to fix, try: `conda install pyqtnetworkview --use-local --c conda-forge`.
tinycss2 package is not available in main conda repository.

**Comment by Adafede** [comment]
Ya...did it, cf my edit, happy to see finally coming to the point x)

**Comment by n-elie** [comment]
You are using main repository for PyQtNetworkView but dev for metgem, that's why you are getting this new error. Just clone dev and compile again and you will be good.

**Comment by Adafede** [comment]
You'll desserve crown after it, but when compiling again with the dev version:

 No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Copying /Users/rutza/Documents/GitHub/PyQtNetworkView to /anaconda3/conda-bld/pyqtnetworkview_1556278263188/work
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for pyqtnetworkview
INFO:conda_build.metadata:Attempting to finalize metadata for pyqtnetworkview
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['pyqtnetworkview-0.2.0-py37_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h1de35cc_1002      conda-forge
    ca-certificates: 2019.3.9-hecc5488_0      conda-forge
    certifi:         2019.3.9-py37_0          conda-forge
    dbus:            1.13.6-h2f22bb5_0        conda-forge
    expat:           2.2.5-h0a44026_1002      conda-forge
    gettext:         0.19.8.1-h46ab8bc_1002   conda-forge
    glib:            2.58.3-h2836805_1001     conda-forge
    icu:             58.2-h0a44026_1000       conda-forge
    jpeg:            9c-h1de35cc_1001         conda-forge
    libcxx:          8.0.0-2                  conda-forge
    libcxxabi:       8.0.0-2                  conda-forge
    libffi:          3.2.1-h6de7cb9_1006      conda-forge
    libiconv:        1.15-h01d97ff_1005       conda-forge
    libpng:          1.6.37-h2573ce8_0        conda-forge
    ncurses:         6.1-h0a44026_1002        conda-forge
    openssl:         1.1.1b-h01d97ff_2        conda-forge
    pcre:            8.41-h0a44026_1003       conda-forge
    pip:             19.1-py37_0              conda-forge
    pyqt:            5.9.2-py37h655552a_2                
    python:          3.7.3-h0d93f26_0         conda-forge
    qt:              5.9.7-h93ee506_1         conda-forge
    readline:        7.0-hcfe32e1_1001        conda-forge
    setuptools:      41.0.1-py37_0            conda-forge
    sip:             4.19.8-py37h0a44026_1000 conda-forge
    sqlite:          3.26.0-h1765d9f_1001     conda-forge
    tk:              8.6.9-ha441bb4_1001      conda-forge
    wheel:           0.33.1-py37_0            conda-forge
    xz:              5.2.4-h1de35cc_1001      conda-forge
    zlib:            1.2.11-h1de35cc_1004     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
source tree in: /anaconda3/conda-bld/pyqtnetworkview_1556278263188/work
export PREFIX=/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export SRC_DIR=/anaconda3/conda-bld/pyqtnetworkview_1556278263188/work
Traceback (most recent call last):
  File "setup.py", line 325, in <module>
    zip_safe=False
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    not self.always_copy, self.local_index
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/package_index.py", line 658, in fetch_distribution
    self.find_packages(requirement)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/package_index.py", line 491, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/package_index.py", line 831, in scan_url
    self.process_url(url, True)
  File "/anaconda3/conda-bld/pyqtnetworkview_1556278263188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.7/site-packages/setuptools/package_index.py", line 326, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%s" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/PyQt5/
Traceback (most recent call last):
  File "/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/anaconda3/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/anaconda3/conda-bld/pyqtnetworkview_1556278263188/work/conda_build.sh']' returned non-zero exit status 1.

So I cannot install it later. Should I try with main from Metgem instead of dev and then use all mains only?

**Comment by Adafede** [comment]
I'm able to run v1.1  *_* *_* *_*

Thank you so much for your help and time!

**Comment by n-elie** [comment]
It's a step forward.
However, I am not sure you are compiling the dev version of PyQtNetworkView because the version should be 0.3.0 instead of 0.2.0

**Comment by n-elie** [comment]
I'm having the same problem building PyQtNetworkView on MacOS. It works fine under Windows

**Comment by n-elie** [comment]
So, I fixed the error in the latest commits. Could you have a try?
Just do a `git pull` in PyQtNetworkView  (you cloned repositories using git, right?)
I also wrote a small (uh, not so small) list of steps needed to make everything work: https://github.com/metgem/metgem/wiki/Compilation-Steps

I was able to build and run MetGem on MacOS X but unfortunately packaging do not work.

**Comment by n-elie** [comment]
Here it is!
I finally managed to produce a .dmg: https://github.com/metgem/metgem/releases/tag/v1.2RC3
Very excited to see if this will work on someone else mac...

**Comment by Adafede** [comment]
Simply amazing! 

Thank you for your work

**Comment by n-elie** [comment]
Newly released version 1.2 has a MacOS X build, so I'll close this issue
