### ISSUE TITLE
DIA mode data 

### ISSUE THREAD

**Issue by M123hx** [metgem/metgem#83]
Hello, Thanks for  your  work on MetGem software  and I am very interested in it. My DIA mode LC-MS/MS data was  acquired by SCIEX Triple TOF, and  and I would like to konw if I can use MetGem to generate molecular networking with MZmine 2 preprocessing DIA data.

Best wishes!

**Comment by n-elie** [comment]
Hello,

Thank you for your interest in this project.
Unfortunately, MetGem can not handle DIA analyses. But this could change in the future, even if not planned for now.

Nicolas

**Comment by Sukis123** [comment]
Hi, Can MetGem handle DIA data now? The DIA data has already been deconvoluted by MS-DIAL and cleaned by MScleanR.
