### ISSUE TITLE
Problem to import user database

### ISSUE THREAD

**Issue by JustineDemay** [metgem/metgem#84]
Hello,
I would like to import a personal database from an msp file but it doesn't work (see capture attached).
Can you help me with this issue ?

Thank you in advance,
Cordially,

Justine Demay

![Capture_bug metgem](https://user-images.githubusercontent.com/62054371/76401640-823aa080-6382-11ea-8198-d696342f0688.PNG)

**Comment by n-elie** [comment]
Hello,

Could you please attach a minimal msp file that will make MetGem crash? I was not able to reproduce the error.

Nicolas

**Comment by JustineDemay** [comment]
Hello, 

Please find the link to download the msp file I would like to import : 

https://we.tl/t-kfvUjJfhte 

Thank you, 
Justine 


Justine DEMAY 

Doctorante 
Thermes de Balaruc-les-Bains 
Muséum National d'Histoire Naturelle 
UMR 7245 Molécules de Communication et Adaptation des Micro-organismes 
Equipe "Cyanobactéries, Cyanotoxines et Environnement" 
12 rue Buffon - RDC Bâtiment de cryptogamie - CP39 
75231 Paris Cedex 05 
France 
Tel : 01 40 79 31 79 
email : justine.demay@edu.mnhn.fr 


De: "n-elie" <notifications@github.com> 
À: "metgem/metgem" <metgem@noreply.github.com> 
Cc: "Justine DEMAY" <justine.demay@edu.mnhn.fr>, "Manual" <manual@noreply.github.com> 
Envoyé: Lundi 23 Mars 2020 14:19:29 
Objet: Re: [metgem/metgem] Problem to import user database (#84) 





Hello, 

Could you please attach a minimal msp file that will make MetGem crash? I was not able to reproduce the error. 

Nicolas

**Comment by n-elie** [comment]
Hello,
I just published a pre-release of a new version: [here](https://github.com/metgem/metgem/releases/tag/v1.3.0RC2)
Could you please have a look and let me know if the problem is still here?
Nicolas
