### ISSUE TITLE
Issue of system compatible

### ISSUE THREAD

**Issue by Shivooz** [metgem/metgem#88]
Metgem can't be open in MAC OS BigSur Version 11.2.3, please fix the problem.
Thanks, Xin Wu

**Comment by n-elie** [comment]
Hello,

I don't have access to this version of Mac OS. Could you provide me more information about what is not working?
You could try to launch MetGem from the command line and post the output.

Nicolas

**Comment by n-elie** [comment]
Hello,

 I finally found a work-around. Could you try to a terminal and type the following commands?
```
export QT_MAC_WANTS_LAYER=1
/Applications/MetGem/MetGem.app/Contents/MacOS/MetGem
```

**Comment by n-elie** [comment]
Hello,

I finally found a work-around. Could you start a terminal on you Mac and type the following commands to start MetGem?
```sh
export QT_MAC_WANTS_LAYER=1
/Applications/MetGem/MetGem.app/Contents/MacOS/MetGem
```
This should fix your problem. Please let me know if it works.

Nicolas

**Comment by n-elie** [comment]
Latest nightly should fix the problem: https://github.com/metgem/metgem/releases/download/nightly/MetGem-20210406-8b1713.dmg

**Comment by Shivooz** [comment]
Hi Nicolas,The version of above link can be used on my MacBook.
Thanks for your answer!
Xin Wu
&nbsp;
------------------
看事要淡，做事要拼。。。


&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Nicolas Elie"; 
Sendtime: Tuesday, Apr 6, 2021 8:40 PM
To: "metgem/metgem"; 
Cc: "WuHsin"; "Author"; 
Subject: Re: [metgem/metgem] Issue of system compatible (#88)





 
Latest nightly should fix the problem: https://github.com/metgem/metgem/releases/download/nightly/MetGem-20210406-8b1713.dmg

**Comment by n-elie** [comment]
Good to hear
