### ISSUE TITLE
matplotlib loading failed

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#89]
Hi Nicolas,
I can't run the last nightly (20210413) neither on my PC nor on my mac.
It crash when loading matplotlib on both system.

Sincerely
Simon

**Comment by n-elie** [comment]
Hi Simon,

I changed the code to support newer versions of matplotlib a few days ago but there is a bug with pyinstaller (library used to package MetGem) that makes it incompatible with latest version of matplotlib: pyinstaller/pyinstaller@de2df24
So I update pyinstaller to 4.3 in metgem/metgem@b978122.
But there is a new bug in pyinstaller 4.3 (pyinstaller/pyinstaller@2897241) that prevent MetGem to start on Windows. This one is also fixed, we'll just have to wait a few days that a new version of pyinstaller is released.

Nicolas

**Comment by n-elie** [comment]
Fixed in f1193a4a313681626f86ccf04279a61b94ea1a4d
