### ISSUE TITLE
'Network' object has no attribute 'mappings'

### ISSUE THREAD

**Issue by simremy** [metgem/metgem#90]
Hello Nicolas, 

Here is a bug report occurring  when importing a GM file on MetGem-20210426-b97812 :

```Traceback (most recent call last):
File "metgem_app/ui/main_window.py", line 2663, in finished
AttributeError: 'Network' object has no attribute 'mappings'
```

Take care
Simon

**Comment by n-elie** [comment]
Hello Simon,
Thanks for the bug report. This is fixed in 20719fb94702cbaa1e57768326f52d0669ffa19e.
Nicolas
